const universes = [
  {
    id: "marvel_cinematic_universe",
    title: "Marvel Cinematic Universe",
    banner_url: "https://i.postimg.cc/zfbW5LMR/marvel.webp",
    description:
      "A complete collection of all Marvel titles in order, starting with Blade (1998). This list includes MCU, X-Men, Spider-Man, Fantastic Four, and more. It covers all Movies, TV shows, one-shots, and specials.",
  },
];

const titles = [
  {
    universe_id: "marvel_cinematic_universe",
    id: "blade",
    title: "Blade",
    branch: "Blade",
    type: "Movie",
    banner_url: "https://i.postimg.cc/MHz0PG56/blade.webp",
    release_date: "1998-08-21",
    duration: 120,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "x-men",
    title: "X-Men",
    branch: "X-Men/Wolverine",
    type: "Movie",
    banner_url: "https://i.postimg.cc/7PQbQ6mK/x-men.webp",
    release_date: "2000-07-14",
    duration: 104,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "blade_2",
    title: "Blade II",
    branch: "Blade",
    type: "Movie",
    banner_url: "https://i.postimg.cc/wTy3Kprg/blade-2.webp",
    release_date: "2002-03-22",
    duration: 117,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "spider-man",
    title: "Spider-Man",
    branch: "Spider-Man",
    type: "Movie",
    banner_url: "https://i.postimg.cc/jjDt7wN1/spider-man.webp",
    release_date: "2002-06-07",
    duration: 121,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "daredevil",
    title: "Daredevil",
    branch: "Daredevil",
    type: "Movie",
    banner_url: "https://i.postimg.cc/MGDp0Knb/daredevil.webp",
    release_date: "2003-02-14",
    duration: 133,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "x2",
    title: "X2",
    branch: "X-Men/Wolverine",
    type: "Movie",
    banner_url: "https://i.postimg.cc/jSkZMxjG/x2.webp",
    release_date: "2003-05-02",
    duration: 133,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "hulk",
    title: "Hulk",
    branch: "Hulk",
    type: "Movie",
    banner_url: "https://i.postimg.cc/gkC4mnwk/hulk.webp",
    release_date: "2003-06-17",
    duration: 138,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_punisher",
    title: "The Punisher",
    branch: "Punisher",
    type: "Movie",
    banner_url: "https://i.postimg.cc/43PnyxLY/the-punisher.webp",
    release_date: "2004-04-16",
    duration: 140,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "spider-man_2",
    title: "Spider Man 2",
    branch: "Spider-Man",
    type: "Movie",
    banner_url: "https://i.postimg.cc/5tVq7XVK/spider-man-2.webp",
    release_date: "2004-07-16",
    duration: 127,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "blade_trinity",
    title: "Blade: Trinity",
    branch: "Blade",
    type: "Movie",
    banner_url: "https://i.postimg.cc/3WMK5B9Y/blade-trinity.webp",
    release_date: "2004-12-08",
    duration: 123,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "elektra",
    title: "Elektra",
    branch: "Daredevil",
    type: "Movie",
    banner_url: "https://i.postimg.cc/C1q6f9Wg/elektra.webp",
    release_date: "2005-01-14",
    duration: 104,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "fantastic_four",
    title: "Fantastic Four",
    branch: "Fantastic Four",
    type: "Movie",
    banner_url: "https://i.postimg.cc/KzBJYBMc/fantastic-four.webp",
    release_date: "2005-07-08",
    duration: 106,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "x-men_the_last_stand",
    title: "X-Men: The Last Stand",
    branch: "X-Men/Wolverine",
    type: "Movie",
    banner_url: "https://i.postimg.cc/q7hdjb9m/x-men-the-last-stand.webp",
    release_date: "2006-05-25",
    duration: 104,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "ghost_rider",
    title: "Ghost Rider",
    branch: "Ghost Rider",
    type: "Movie",
    banner_url: "https://i.postimg.cc/639CS5YB/ghost-rider.webp",
    release_date: "2007-02-16",
    duration: 114,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "spider-man_3",
    title: "Spider-Man 3",
    branch: "Spider-Man/Venom",
    type: "Movie",
    banner_url: "https://i.postimg.cc/6pPk2VyC/spider-man-3.webp",
    release_date: "2007-05-04",
    duration: 139,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "fantastic_four_rise_of_the_silver_surfer",
    title: "Fantastic Four: Rise of the Silver Surfer",
    branch: "Fantastic Four",
    type: "Movie",
    banner_url:
      "https://i.postimg.cc/MHzN2dFJ/fantastic-four-rise-of-the-silver-surfer.webp",
    release_date: "2007-06-15",
    duration: 92,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "iron_man",
    title: "Iron Man",
    branch: "Iron Man",
    type: "Movie",
    banner_url: "https://i.postimg.cc/nzFT3XJY/iron-man.webp",
    release_date: "2008-05-02",
    duration: 126,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_incredible_hulk",
    title: "The Incredible Hulk",
    branch: "Hulk",
    type: "Movie",
    banner_url: "https://i.postimg.cc/FzmyT6n3/the-incredible-hulk.webp",
    release_date: "2008-06-13",
    duration: 112,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "punisher_war_zone",
    title: "Punisher: War Zone",
    branch: "Punisher",
    type: "Movie",
    banner_url: "https://i.postimg.cc/wTMy9HJ3/punisher-war-zone.webp",
    release_date: "2008-12-05",
    duration: 107,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "x-men_origins_wolverine",
    title: "X-Men Origins: Wolverine",
    branch: "X-Men/Wolverine",
    type: "Movie",
    banner_url: "https://i.postimg.cc/Hs6wtB08/x-men-origins-wolverine.webp",
    release_date: "2009-05-01",
    duration: 107,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "iron_man_2",
    title: "Iron Man 2",
    branch: "Iron Man/Black Widow",
    type: "Movie",
    banner_url: "https://i.postimg.cc/wTjJ3DKq/iron-man-2.webp",
    release_date: "2010-04-30",
    duration: 125,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "thor",
    title: "Thor",
    branch: "Thor/Loki/Hawkeye",
    type: "Movie",
    banner_url: "https://i.postimg.cc/WbYZZtjM/thor.webp",
    release_date: "2011-05-06",
    duration: 114,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "x-men_first_class",
    title: "X-Men: First Class",
    branch: "X-Men",
    type: "Movie",
    banner_url: "https://i.postimg.cc/Gms4sQXC/x-men-first-class.webp",
    release_date: "2011-05-25",
    duration: 132,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "captain_america_the_first_avenger",
    title: "Captain America: The First Avenger",
    branch: "Captain America",
    type: "Movie",
    banner_url:
      "https://i.postimg.cc/Z5TRprNV/captain-america-the-fisrt-avenger.webp",
    release_date: "2011-07-22",
    duration: 124,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_consultant",
    title: "The Consultant",
    branch: "Avengers/Agents of S.H.I.E.L.D.",
    type: "One-Shot",
    banner_url: "https://i.postimg.cc/fLWW5jfk/the-consultant.webp",
    release_date: "2011-09-11",
    duration: 4,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "a_funny_thing_happened_on_the_way_to_thors_hammer",
    title: "A Funny Thing Happened on the Way to Thor's Hammer",
    branch: "Avengers/Agents of S.H.I.E.L.D.",
    type: "One-Shot",
    banner_url:
      "https://i.postimg.cc/9MxmkRLb/a-funny-thing-happened-on-the-way-to-thors-hammer.webp",
    release_date: "2011-10-25",
    duration: 4,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "ghost_rider_spirit_of_vengeance",
    title: "Ghost Rider: Spirit of Vengeance",
    branch: "Ghost Rider",
    type: "Movie",
    banner_url:
      "https://i.postimg.cc/1X29mxhN/ghost-rider-spirit-of-vengeance.webp",
    release_date: "2012-02-17",
    duration: 96,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_avengers",
    title: "The Avengers",
    branch:
      "Avengers/Iron Man/Captain America/Hulk/Thor/Loki/Black Widow/Hawkeye",
    type: "Movie",
    banner_url: "https://i.postimg.cc/0ydq3KQS/the-avengers.webp",
    release_date: "2012-05-04",
    duration: 143,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_amazing_spider_man",
    title: "The Amazing Spider-Man",
    branch: "Spider-Man",
    type: "Movie",
    banner_url: "https://i.postimg.cc/T3RRTJB0/the-amazing-spider-man.webp",
    release_date: "2012-07-03",
    duration: 136,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "item_47",
    title: "Item 47",
    branch: "Avengers",
    type: "One-Shot",
    banner_url: "https://i.postimg.cc/k4tCT1tJ/item-47.webp",
    release_date: "2012-09-25",
    duration: 12,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "iron_man_3",
    title: "Iron Man 3",
    branch: "Iron Man",
    type: "Movie",
    banner_url: "https://i.postimg.cc/WzLp3rjm/iron-man-3.webp",
    release_date: "2013-05-03",
    duration: 130,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_wolverine",
    title: "The Wolverine",
    branch: "Wolverine",
    type: "Movie",
    banner_url: "https://i.postimg.cc/qMcqNmNN/the-wolverine.webp",
    release_date: "2013-07-26",
    duration: 126,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "agent_carter",
    title: "Agent Carter",
    branch: "Agents of S.H.I.E.L.D.",
    type: "One-Shot",
    banner_url: "https://i.postimg.cc/50q1CPY6/agent-carter.webp",
    release_date: "2013-09-23",
    duration: 15,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "agents_of_shield_s1",
    title: "Agents of S.H.I.E.L.D. Season 1",
    branch: "Agents of S.H.I.E.L.D.",
    type: "Series",
    banner_url: "https://i.postimg.cc/tRnd5pFn/agents-of-shield-s1.webp",
    release_date: "2013-09-24",
    duration: 957,
  },

  {
    universe_id: "marvel_cinematic_universe",
    id: "thor_the_dark_world",
    title: "Thor: The Dark World",
    branch: "Thor/Loki",
    type: "Movie",
    banner_url: "https://i.postimg.cc/VLGgDfGX/thor-the-dark-world.webp",
    release_date: "2013-11-08",
    duration: 112,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "all_hail_the_king",
    title: "All Hail The King",
    branch: "Iron Man",
    type: "One-Shot",
    banner_url: "https://i.postimg.cc/fTknzWK3/all-hail-the-king.webp",
    release_date: "2014-02-04",
    duration: 14,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "captain_america_the_winter_soldier",
    title: "Captain America: The Winter Soldier",
    branch: "Captain America/Black Widow",
    type: "Movie",
    banner_url:
      "https://i.postimg.cc/Hshb83CY/captain-america-the-winter-soldier.webp",
    release_date: "2014-04-04",
    duration: 136,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_amazing_spider_man_2",
    title: "The Amazing Spider-Man 2",
    branch: "Spider-Man",
    type: "Movie",
    banner_url: "https://i.postimg.cc/x1q24d0Q/the-amazing-spider-man-2.webp",
    release_date: "2014-05-02",
    duration: 142,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "x-men-days-of-future-past",
    title: "X-Men: Days of Future Past",
    branch: "X-Men/Wolverine",
    type: "Movie",
    banner_url: "https://i.postimg.cc/YqhDcLmd/x-men-days-of-future-past.webp",
    release_date: "2014-05-23",
    duration: 151,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "guardians_of_the_galaxy",
    title: "Guardians of the Galaxy",
    branch: "Guardians of the Galaxy",
    type: "Movie",
    banner_url: "https://i.postimg.cc/DzgP47XW/guardians-of-the-galaxy.webp",
    release_date: "2014-08-01",
    duration: 122,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "agents_of_shield_s2",
    title: "Agents of S.H.I.E.L.D. Season 2",
    branch: "Agents of S.H.I.E.L.D.",
    type: "Series",
    banner_url: "https://i.postimg.cc/tC03vwzS/agents-of-shield-s2.webp",
    release_date: "2014-09-23",
    duration: 957,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "agent_carter_s1",
    title: "Agent Carter season 1",
    branch: "Agents of S.H.I.E.L.D.",
    type: "Series",
    banner_url: "https://i.postimg.cc/ht85MWmn/agent-carter-s1.webp",
    release_date: "2015-01-06",
    duration: 340,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "daredevil_s1",
    title: "Daredevil season 1",
    branch: "Daredevil",
    type: "Series",
    banner_url: "https://i.postimg.cc/dQxPTY2S/daredevil-s1.webp",
    release_date: "2015-04-10",
    duration: 721,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "avengers_age_of_ultron",
    title: "Avengers: Age of Ultron",
    branch:
      "Avengers/Iron Man/Captain America/Hulk/Thor/Scarlet Witch/Black Widow/Hawkeye",
    type: "Movie",
    banner_url: "https://i.postimg.cc/mDkpbP5Z/avengers-age-of-altron.webp",
    release_date: "2015-05-01",
    duration: 141,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "ant_man",
    title: "Ant-Man",
    branch: "Ant-Man",
    type: "Movie",
    banner_url: "https://i.postimg.cc/Jny5Nsgd/ant-man.webp",
    release_date: "2015-06-15",
    duration: 118,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "agents_of_shield_s3",
    title: "Agents of S.H.I.E.L.D. season 3",
    branch: "Agents of S.H.I.E.L.D.",
    type: "Series",
    banner_url: "https://i.postimg.cc/W4vw1SxT/agents-of-shield-s3.webp",
    release_date: "2015-09-29",
    duration: 957,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "jessica_jones_s1",
    title: "Jessica Jones season 1",
    branch: "Jessica Jones",
    type: "Series",
    banner_url: "https://i.postimg.cc/6QPb1zq9/jessica-jones-s1.webp",
    release_date: "2015-11-20",
    duration: 656,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "agent_carter_s2",
    title: "Agent Carter season 2",
    branch: "Agents of S.H.I.E.L.D.",
    type: "Series",
    banner_url: "https://i.postimg.cc/m24XqPLF/agent-carter-s2.webp",
    release_date: "2016-01-19",
    duration: 425,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "daredevil_s2",
    title: "Daredevil season 2",
    branch: "Daredevil/Punisher",
    type: "Series",
    banner_url: "https://i.postimg.cc/vmpF6GWL/daredevil-s2.webp",
    release_date: "2016-03-18",
    duration: 721,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "captain_america_civil_war",
    title: "Captain America: Civil War",
    branch:
      "Iron Man/Captain America/Spider-Man/Black Panther/Ant-Man/Scarlet Witch/Black Widow/Hawkeye",
    type: "Movie",
    banner_url: "https://i.postimg.cc/8kx4QjTb/captain-america-civil-war.webp",
    release_date: "2016-05-06",
    duration: 148,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "agents_of_shield_s4",
    title: "Agents of SHIELD season 4",
    branch: "Agents of S.H.I.E.L.D.",
    type: "Series",
    banner_url: "https://i.postimg.cc/VNHMqV6F/agents-of-shield-s4.webp",
    release_date: "2016-09-20",
    duration: 957,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "luke_cage_s1",
    title: "Luke Cage season 1",
    branch: "Luke Cage",
    type: "Series",
    banner_url: "https://i.postimg.cc/7YDC2k9k/luke-cage-s1.webp",
    release_date: "2016-09-30",
    duration: 650,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "doctor_strange",
    title: "Doctor Strange",
    branch: "Doctor Strange",
    type: "Movie",
    banner_url: "https://i.postimg.cc/dVVL5jgN/doctor-strange.webp",
    release_date: "2016-11-04",
    duration: 115,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "iron_fist_s1",
    title: "Iron Fist season 1",
    branch: "Iron Fist",
    type: "Series",
    banner_url: "https://i.postimg.cc/C5Jw8WMh/iron-fist-s1.webp",
    release_date: "2017-03-17",
    duration: 715,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "guardians_of_the_galaxy_vol_2",
    title: "Guardians of the Galaxy Vol. 2",
    branch: "Guardians of the Galaxy",
    type: "Movie",
    banner_url:
      "https://i.postimg.cc/wvgKk0G7/guardians-of-the-galaxy-vol-2.webp",
    release_date: "2017-05-05",
    duration: 137,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "spider-man_homecoming",
    title: "Spider-Man: Homecoming",
    branch: "Iron Man/Spider-Man",
    type: "Movie",
    banner_url: "https://i.postimg.cc/YSBTpdkb/spider-man-homecoming.webp",
    release_date: "2017-07-07",
    duration: 133,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "fantastic_four_2015",
    title: "Fantastic Four",
    branch: "Fantastic Four",
    type: "Movie",
    banner_url: "https://i.postimg.cc/d0WgDRwz/fantastic-four-2015.webp",
    release_date: "2015-08-06",
    duration: 100,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "deadpool",
    title: "Deadpool",
    branch: "Deadpool",
    type: "Movie",
    banner_url: "https://i.postimg.cc/XJmhkVZL/deadpool.webp",
    release_date: "2016-02-12",
    duration: 108,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "x-men_apocalypse",
    title: "X-Men: Apocalypse",
    branch: "X-Men",
    type: "Movie",
    banner_url: "https://i.postimg.cc/SNBgTTxS/x-men-apocalypse.webp",
    release_date: "2016-05-27",
    duration: 144,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "team_thor_part_1",
    title: "Team Thor",
    branch: "Thor",
    type: "One-Shot",
    banner_url: "https://i.postimg.cc/FsFftcD2/team-thor-part-1.webp",
    release_date: "2016-08-28",
    duration: 3,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "team_thor_part_2",
    title: "Team Thor: Part 2",
    branch: "Thor",
    type: "One-Shot",
    banner_url: "https://i.postimg.cc/cHmsTky6/team-thor-part-2.webp",
    release_date: "2017-02-14",
    duration: 5,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "logan",
    title: "Logan",
    branch: "Wolverine",
    type: "Movie",
    banner_url: "https://i.postimg.cc/bv08NVvL/logan.webp",
    release_date: "2017-03-03",
    duration: 137,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "deadpool_no_good_deed",
    title: "Deadpool: No Good Deed",
    branch: "Deadpool",
    type: "One-Shot",
    banner_url: "https://i.postimg.cc/6QtgzW9L/deadpool-no-good-deed.webp",
    release_date: "2017-03-03",
    duration: 4,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_defenders",
    title: "The Defenders",
    branch: "Defenders/Daredevil/Jessica Jones/Luke Cage/Iron Fist",
    type: "Series",
    banner_url: "https://i.postimg.cc/HWzw7TK1/the-defenders.webp",
    release_date: "2017-08-18",
    duration: 400,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "inhumans",
    title: "Inhumans",
    branch: "Inhumans",
    type: "Series",
    banner_url: "https://i.postimg.cc/9QwRQ2Z2/inhumans.webp",
    release_date: "2017-09-29",
    duration: 340,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "thor_ragnarok",
    title: "Thor: Ragnarok",
    branch: "Thor/Hulk/Loki",
    type: "Movie",
    banner_url: "https://i.postimg.cc/pdq3ywDW/thor-ragnarok.webp",
    release_date: "2017-11-03",
    duration: 130,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_punisher_s1",
    title: "The Punisher season 1",
    branch: "Punisher",
    type: "Series",
    banner_url: "https://i.postimg.cc/sxXWsh3f/the-punisher-s1.webp",
    release_date: "2017-11-17",
    duration: 702,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "runaways_s1",
    title: "Runaways season 1",
    branch: "Runaways",
    type: "Series",
    banner_url: "https://i.postimg.cc/vTsnkZmX/runaways-s1.webp",
    release_date: "2017-11-21",
    duration: 475,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "agents_of_shield_s5",
    title: "Agents of S.H.I.E.L.D. season 5",
    branch: "Agents of S.H.I.E.L.D.",
    type: "Series",
    banner_url: "https://i.postimg.cc/kXxC7XgK/agents-of-shield-s5.webp",
    release_date: "2017-12-01",
    duration: 957,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "black_panther",
    title: "Black Panther",
    branch: "Black Panther",
    type: "Movie",
    banner_url: "https://i.postimg.cc/mZ9kF4r2/black-panther.webp",
    release_date: "2018-02-16",
    duration: 134,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "team_darryl",
    title: "Team Darryl",
    branch: "Thor",
    type: "One-Shot",
    banner_url: "https://i.postimg.cc/Z5rq4Lr8/team-darryl.webp",
    release_date: "2018-02-20",
    duration: 6,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "jessica_jones_s2",
    title: "Jessica Jones season 2",
    branch: "Jessica Jones/Luke Cage",
    type: "Series",
    banner_url: "https://i.postimg.cc/VNLkjqwc/jessica-jones-s2.webp",
    release_date: "2018-03-08",
    duration: 682,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "avengers_infinity_war",
    title: "Avengers: Infinity War",
    branch:
      "Avengers/Iron Man/Captain America/Hulk/Thor/Spider-Man/Black Panther/Guardians of the Galaxy/Scarlet Witch/Loki/Black Widow",
    type: "Movie",
    banner_url: "https://i.postimg.cc/9FrR70Kr/avengers-infinity-war.webp",
    release_date: "2018-04-27",
    duration: 149,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "deadpool_2",
    title: "Deadpool 2",
    branch: "Deadpool",
    type: "Movie",
    banner_url: "https://i.postimg.cc/9Qxn46tC/deadpool-2.webp",
    release_date: "2018-05-15",
    duration: 120,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "cloak_&_dagger_s1",
    title: "Cloak & Dagger season 1",
    branch: "Cloak & Dagger",
    type: "Series",
    banner_url: "https://i.postimg.cc/HsrcD5Zz/cloak-dagger.webp",
    release_date: "2018-06-07",
    duration: 425,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "luke_cage_s2",
    title: "Luke Cage season 2",
    branch: "Luke Cage",
    type: "Series",
    banner_url: "https://i.postimg.cc/wjvdbcwx/luke-cage-s2.webp",
    release_date: "2018-06-22",
    duration: 715,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "ant_man_and_the_wasp",
    title: "Ant-Man and the Wasp",
    branch: "Ant-Man",
    type: "Movie",
    banner_url: "https://i.postimg.cc/6pGM383L/ant-man-and-the-wasp.webp",
    release_date: "2018-07-06",
    duration: 118,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "iron_fist_s2",
    title: "Iron Fist season 2",
    branch: "Iron Fist",
    type: "Series",
    banner_url: "https://i.postimg.cc/Sxy6MVmr/iron-fist-s2.webp",
    release_date: "2018-09-07",
    duration: 550,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "venom",
    title: "Venom",
    branch: "Venom",
    type: "Movie",
    banner_url: "https://i.postimg.cc/y8gVvC6Y/venom.webp",
    release_date: "2018-10-01",
    duration: 112,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "daredevil_s3",
    title: "Daredevil season 3",
    branch: "Daredevil",
    type: "Series",
    banner_url: "https://i.postimg.cc/D09ChGGN/daredevil-s3.webp",
    release_date: "2018-10-19",
    duration: 715,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "runaways_s2",
    title: "Runaways season 2",
    branch: "Runaways",
    type: "Series",
    banner_url: "https://i.postimg.cc/bNqgxqTk/runaways-s2.webp",
    release_date: "2018-12-21",
    duration: 475,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_punisher_s2",
    title: "The Punisher season 2",
    branch: "Punisher",
    type: "Series",
    banner_url: "https://i.postimg.cc/sgXJLKb2/the-punisher-s2.webp",
    release_date: "2019-01-18",
    duration: 715,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "captain_marvel",
    title: "Captain Marvel",
    branch: "Captain Marvel",
    type: "Movie",
    banner_url: "https://i.postimg.cc/T2JqYZ6w/captain-marvel.webp",
    release_date: "2019-03-08",
    duration: 124,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "cloak_&_dagger_s2",
    title: "Cloak & Dagger season 2",
    branch: "Cloak & Dagger",
    type: "Series",
    banner_url: "https://i.postimg.cc/TwXgTcNg/cloak-dagger-s2.webp",
    release_date: "2019-04-04",
    duration: 425,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "avengers_endgame",
    title: "Avengers: Endgame",
    branch:
      "Avengers/Iron Man/Captain America/Thor/Hulk/Ant-Man/Captain Marvel/Black Panther/Spider-Man/Doctor Strange/Guardians of the Galaxy/Scarlet Witch/Loki/Black Widow/Hawkeye",
    type: "Movie",
    banner_url: "https://i.postimg.cc/NMY93jLx/avengers-endgame.webp",
    release_date: "2019-04-26",
    duration: 182,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "agents_of_shield_s6",
    title: "Agents of S.H.I.E.L.D. season 6",
    branch: "Agents of S.H.I.E.L.D.",
    type: "Series",
    banner_url: "https://i.postimg.cc/639qHb1j/agents-of-shield-s6.webp",
    release_date: "2019-05-10",
    duration: 559,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "dark_phoenix",
    title: "Dark Phoenix",
    branch: "X-Men",
    type: "Movie",
    banner_url: "https://i.postimg.cc/SxCKmbB1/dark-phoenix.webp",
    release_date: "2019-06-07",
    duration: 114,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "jessica_jones_s3",
    title: "Jessica Jones season 3",
    branch: "Jessica Jones",
    type: "Series",
    banner_url: "https://i.postimg.cc/QtxNg9Hv/jessica-jones-s3.webp",
    release_date: "2019-06-14",
    duration: 682,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "spider-man_far_from_home",
    title: "Spider-Man: Far From Home",
    branch: "Spider-Man",
    type: "Movie",
    banner_url: "https://i.postimg.cc/xTrChd7N/spider-man-far-from-home.webp",
    release_date: "2019-07-02",
    duration: 130,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "peters_to-do_list",
    title: "Peter's To-Do List",
    branch: "Spider-Man",
    type: "One-Shot",
    banner_url: "https://i.postimg.cc/Dyd2NPLR/peters-to-do-list.webp",
    release_date: "2019-09-17",
    duration: 4,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "runaways_s3",
    title: "Runaways season 3",
    branch: "Runaways",
    type: "Series",
    banner_url: "https://i.postimg.cc/RF02dCFq/runaways-s3.webp",
    release_date: "2019-12-13",
    duration: 475,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "agents_of_shield_s7",
    title: "Agents of S.H.I.E.L.D. season 7",
    branch: "Agents of S.H.I.E.L.D.",
    type: "Series",
    banner_url: "https://i.postimg.cc/9Fzp8J6Q/agents-of-shield-s7.webp",
    release_date: "2020-05-27",
    duration: 559,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_new_mutants",
    title: "The New Mutants",
    branch: "X-Men",
    type: "Movie",
    banner_url: "https://i.postimg.cc/TwyffQc0/the-new-mutants.webp",
    release_date: "2020-08-28",
    duration: 94,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "helstrom",
    title: "Helstrom",
    branch: "Helstrom",
    type: "Series",
    banner_url: "https://i.postimg.cc/90RdP3Y9/helstrom.webp",
    release_date: "2020-10-16",
    duration: 450,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "wandavision",
    title: "WandaVision",
    branch: "Scarlet Witch",
    type: "Series",
    banner_url: "https://i.postimg.cc/XqHhmRrx/wandavision.webp",
    release_date: "2021-01-15",
    duration: 360,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_falcon_and_the_winter_soldier",
    title: "The Falcon and the Winter Soldier",
    branch: "Captain America",
    type: "Series",
    banner_url:
      "https://i.postimg.cc/t4Kg8fPX/the-falcon-and-the-winter-soldier.webp",
    release_date: "2021-03-19",
    duration: 300,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "loki_s1",
    title: "Loki season 1",
    branch: "Loki",
    type: "Series",
    banner_url: "https://i.postimg.cc/J4g7Bgpb/loki-s1.webp",
    release_date: "2021-06-09",
    duration: 270,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "black_widow",
    title: "Black Widow",
    branch: "Black Widow",
    type: "Movie",
    banner_url: "https://i.postimg.cc/DwjNZk5T/black-widow.webp",
    release_date: "2021-07-09",
    duration: 133,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "shang-chi_and_the_legend_of_the_ten_rings",
    title: "Shang-Chi and the Legend of the Ten Rings",
    branch: "Shang-Chi",
    type: "Movie",
    banner_url:
      "https://i.postimg.cc/fTBsxP5H/shang-chi-and-the-legend-of-the-ten-rings.webp",
    release_date: "2021-09-02",
    duration: 132,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "venom_let_there_be_carnage",
    title: "Venom: Let There Be Carnage",
    branch: "Venom",
    type: "Movie",
    banner_url: "https://i.postimg.cc/FRWbbNdr/venom-let-there-be-carnage.webp",
    release_date: "2021-10-01",
    duration: 97,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "eternals",
    title: "Eternals",
    branch: "Eternals",
    type: "Movie",
    banner_url: "https://i.postimg.cc/XqYRf7BY/eternals.webp",
    release_date: "2021-11-05",
    duration: 157,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "hawkeye",
    title: "Hawkeye",
    branch: "Hawkeye",
    type: "Series",
    banner_url: "https://i.postimg.cc/fLPr47gY/hawkeye.webp",
    release_date: "2021-11-24",
    duration: 300,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "spider-man_no_way_home",
    title: "Spider-Man: No Way Home",
    branch: "Spider-Man/Doctor Strange",
    type: "Movie",
    banner_url: "https://i.postimg.cc/8zHG23dW/spider-man-now-way-home.webp",
    release_date: "2021-12-17",
    duration: 148,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "moon_knight",
    title: "Moon Knight",
    branch: "Moon Knight",
    type: "Series",
    banner_url: "https://i.postimg.cc/GpgC2y5m/moon-knight.webp",
    release_date: "2022-03-30",
    duration: 300,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "morbius",
    title: "Morbius",
    branch: "Morbius",
    type: "Movie",
    banner_url: "https://i.postimg.cc/FsXQ7mD3/morbius.webp",
    release_date: "2022-04-01",
    duration: 104,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "doctor_strange_in_the_multiverse_of_madness",
    title: "Doctor Strange in the Multiverse of Madness",
    branch: "Doctor Strange/Scarlet Witch",
    type: "Movie",
    banner_url:
      "https://i.postimg.cc/FHPqgQgP/doctor-strange-in-the-multiverse-of-madness.webp",
    release_date: "2022-05-06",
    duration: 126,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "ms_marvel",
    title: "Ms. Marvel",
    branch: "Ms. Marvel",
    type: "Series",
    banner_url: "https://i.postimg.cc/sf9T4r3p/ms-marvel.webp",
    release_date: "2022-06-08",
    duration: 277,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "thor_love_and_thunder",
    title: "Thor: Love and Thunder",
    branch: "Thor/Guardians of the Galaxy",
    type: "Movie",
    banner_url: "https://i.postimg.cc/8zswGfMH/thor-love-and-thunder.webp",
    release_date: "2022-07-06",
    duration: 119,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "i_am_groot_s1",
    title: "I Am Groot season 1",
    branch: "Guardians of the Galaxy",
    type: "Series",
    banner_url: "https://i.postimg.cc/pdFZhN05/i-am-groot-s1.webp",
    release_date: "2022-08-10",
    duration: 72,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "she-hulk_uttorney_at_law",
    title: "She-Hulk: Attorney at Law",
    branch: "Hulk",
    type: "Series",
    banner_url: "https://i.postimg.cc/GtcJ54bv/she-hulk-attorney-at-law.webp",
    release_date: "2022-08-18",
    duration: 324,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "werewolf_by_night",
    title: "Werewolf by Night",
    branch: "Werewolf",
    type: "Special",
    banner_url: "https://i.postimg.cc/KjJrSmYw/werewolf-by-night.webp",
    release_date: "2022-10-07",
    duration: 50,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "black_panther_wakanda_forever",
    title: "Black Panther: Wakanda Forever",
    branch: "Black Panther",
    type: "Movie",
    banner_url:
      "https://i.postimg.cc/t4LdHSXq/black-panther-wakanda-forever.webp",
    release_date: "2022-11-11",
    duration: 161,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_quardians_of_the_galaxy_holiday_special",
    title: "The Guardians of the Galaxy Holiday Special",
    branch: "Guardians of the Galaxy",
    type: "Special",
    banner_url:
      "https://i.postimg.cc/mDS7CT7k/guardians-of-the-galaxy-holiday-special.webp",
    release_date: "2022-11-25",
    duration: 42,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "ant_man_and_the_wasp_quantomania",
    title: "Ant-Man and The Wasp: Quantumania",
    branch: "Ant-Man",
    type: "Movie",
    banner_url:
      "https://i.postimg.cc/L8Zfvtjr/ant-man-and-the-wasp-quantomania.webp",
    release_date: "2023-02-17",
    duration: 125,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "guardians_of_the_galaxy_vol_3",
    title: "Guardians of the Galaxy Vol. 3",
    branch: "Guardians of the Galaxy",
    type: "Movie",
    banner_url:
      "https://i.postimg.cc/wxfmpfVC/guardians-of-the-galaxy-vol-3.webp",
    release_date: "2023-05-05",
    duration: 149,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "secret_invasion",
    title: "Secret Invasion",
    branch: "Avengers",
    type: "Series",
    banner_url: "https://i.postimg.cc/yd6DqcS6/secret-invasion.webp",
    release_date: "2023-06-21",
    duration: 324,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "i_am_groot_s2",
    title: "I Am Groot season 2",
    branch: "Guardians of the Galaxy",
    type: "Series",
    banner_url: "https://i.postimg.cc/J72Ggy7m/i-am-groot-s2.webp",
    release_date: "2023-09-06",
    duration: 25,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "loki_s2",
    title: "Loki season 2",
    branch: "Loki",
    type: "Series",
    banner_url: "https://i.postimg.cc/qqPB73g3/loki-s2.webp",
    release_date: "2023-10-05",
    duration: 294,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_marvels",
    title: "The Marvels",
    branch: "Captain Marvel/Ms. Marvel",
    type: "Movie",
    banner_url: "https://i.postimg.cc/9QjF5Z63/the-marvels.webp",
    release_date: "2023-11-10",
    duration: 105,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "echo",
    title: "Echo",
    branch: "Daredevil",
    type: "Series",
    banner_url: "https://i.postimg.cc/vBjbPVrN/echo.webp",
    release_date: "2024-01-09",
    duration: 225,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "madame_web",
    title: "Madame Web",
    branch: "Spider-Man",
    type: "Movie",
    banner_url: "https://i.postimg.cc/T3R15nCV/madame-web.webp",
    release_date: "2024-02-14",
    duration: 116,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "deadpool_&_wolverine",
    title: "Deadpool & Wolverine",
    branch: "Deadpool/Wolverine/Blade",
    type: "Movie",
    banner_url: "https://i.postimg.cc/5yT5NnwS/deadpool-wolverine.webp",
    release_date: "2024-07-25",
    duration: 127,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "legion_s1",
    title: "Legion season 1",
    branch: "Legion",
    type: "Series",
    banner_url: "https://i.postimg.cc/s2CjHFwF/legion-s1.webp",
    release_date: "2017-02-08",
    duration: 409,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "legion_s2",
    title: "Legion season 2",
    branch: "Legion",
    type: "Series",
    banner_url: "https://i.postimg.cc/GhBbc3fw/legion-s2.webp",
    release_date: "2018-04-03",
    duration: 585,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "legion_s3",
    title: "Legion season 3",
    branch: "Legion",
    type: "Series",
    banner_url: "https://i.postimg.cc/GpjCM44Y/legion-s3.webp",
    release_date: "2019-06-24",
    duration: 342,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_gifted_s1",
    title: "The Gifted season 1",
    branch: "The Gifted",
    type: "Series",
    banner_url: "https://i.postimg.cc/Pf7kFs56/the-gifted-s1.webp",
    release_date: "2017-10-02",
    duration: 554,
  },
  {
    universe_id: "marvel_cinematic_universe",
    id: "the_gifted_s2",
    title: "The Gifted season 2",
    branch: "The Gifted",
    type: "Series",
    banner_url: "https://i.postimg.cc/c48Gp9Kd/the-gifted-s2.webp",
    release_date: "2018-09-25",
    duration: 711,
  },
  // {
  //   universe_id: "marvel_cinematic_universe",
  //   id: "",
  //   title: "",
  //   branch: "",
  //   type: "",
  //   banner_url: "",
  //   release_date: "",
  //   duration: 0,
  // },
];

module.exports = { universes, titles };
